### PR TITLE
Add support for multiple clients

### PR DESCRIPTION
**Pull request by wch**
This is a work in progress -- I want to get some feedback before going too much further.

In this pull request I've separated the clients from the server. The `shinyapp` class still directly controls the R/Shiny process, but the clients are contained `self$clients`, which is a list of `shinyapp_client` objects. By default, there is one client per app, but more could be used. I suppose zero could be used as well, if mock-session testing is used.

I haven't tested out many things yet, but this currently works:

```R
app <- shinyapp$new("tests/testthat/apps/081-widgets-gallery", clients = 2)
app$clients[[1]]$get_value("checkbox")
# [1] TRUE
app$clients[[2]]$get_value("checkbox")
# [1] TRUE
```

I also haven't yet taken out all the methods from `shinyapp`, like `app$get_value()`. Those could be kept around as a shorthand for  `app$clients[[1]]$get_value()`, though I'm not sure that's worth the trouble.

What do you think?

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I think it looks pretty good. 

Focusing on the user-facing API, I think the key question is whether we want users to know about the `client` class/objects at all. I think it is fine for advanced users to know about it, but it would be great if beginners wouldn't have to deal with it.

@daattali liked the `app$set_value` / `app$get_value` API because it is easier to read and write, and I think it makes sense to support it, and also similar methods, e.g.`get_source`, `send_keys`, etc. I don't think it is a much hassle, as I see the biggest task is having to write docs/tutorials for them. 

But they also allow a gradual introduction to Shiny testing, and I like this a lot:
1. Just work with the `app` class and `test_app` / `expect_update`, don't even need to know about `widget`, `client`, etc. This makes it very simple to get started.
2. Work with the `widget`s directly. This will be needed for more complicated widgets, e.g. plots or tables, where you need some sophistication over just doing `get_value()` and `set_value()`.
3. Work with the HTML/JS under the widgets: `get_element()` on a widget, or `find_elements()` on the app itself. Users still do not need to know about clients.
4. Work with `client`s for multi-client testing.

I think there are a bunch of potential improvements, e.g. naming clients, having a *default* client, etc., but we can deal with these later, and multiple clients being an advanced feature, I am not even sure if we need them.

**Comment by daattali** [comment]
100% agree that the typical user should not have to deal with clients, it'd be better if it's an advanced feature that's available but not necessary to understand

**Comment by gaborcsardi** [comment]
Another high level comment about the implementation. The phantom webdriver supports multiple sessions, and I am pretty sure that other webdriver implementations support them as well.

I think it would make sense to try to use a single phantom process, and multiple sessions for the multiple clients. This makes our code a bit more complicated, but I think it is just a good idea to minimize the number of external processes. 

If it turns out that this approach does not work well (which is entirely possible), we can still use multiple processes, but I would try the single-process multiple-sessions approach first.

**Comment by wch** [comment]
Good idea to use a single phantomjs process. I was actually thinking that it would be nice to persist the phantomjs process across applications, so that the price of starting it up can be paid just once.

I'll modify the `app_get_value` (and similar) functions so that it accesses from the first client. That way, most users don't need to know about the client.

**Comment by wch** [comment]
I'm actually going to close this PR aside for now and possibly come back to the topic later.

**Comment by gaborcsardi** [comment]
>  I was actually thinking that it would be nice to persist the phantomjs process across applications, so that the price of starting it up can be paid just once.

Good idea. `testthat` does not really have methods to run code before and after the tests, ideally we would need that. But we can probably work around it. We would also need a better way to detect if phantom webdriver is ready to serve connections, because this is sometimes a problem if the startup is slow. https://github.com/MangoTheCat/webdriver/issues/32

**Comment by gaborcsardi** [comment]
@wch I updated the package to have a single phantom process. It is automatically (re)started if it is not running, or it is not answering http requests. 

FYI, in case you want to rewrite this PR.

**Pull request closed without merging**
