### PR TITLE
Inject Javascript using webdriver

### PR DESCRIPTION
**Pull request by wch**
Instead of injecting Javascript into the raw HTML of the Shiny application, this uses webdriver to execute the contents of shiny-tracer.js. This is one component needed to make it possible to run tests on a remote server.

One notable change is that shiny-tracer.js generally won't be loaded before the client establishes a websocket (Shiny) connection to the server.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
> One notable change is that shiny-tracer.js generally won't be loaded before the client establishes a websocket (Shiny) connection to the server.

Yes, this was my original reason for doing it the other way. If you have an app that starts updating immediately, injecting the script via webdriver might be too late. 

I don't know if webdriver/phantom has a way of running some script _before_ the script on the page runs. I didn't look too carefully.

Also, I am not sure how important it is to load the tracer before Shiny. By the time you start the tests, the app might have updated some widgets, anyway. Once this that you miss is some Shiny events. These would be nice to log I think.

But being able to run on a remote server is a big plus, so I agree with this change in general.

**Comment by wch** [comment]
> I don't know if webdriver/phantom has a way of running some script before the scripts on the page run. I didn't look too carefully.

I just looked a little bit and found this, but it doesn't sound promising:
http://stackoverflow.com/questions/31354352/selenium-how-to-inject-execute-a-javascript-in-to-a-page-before-loading-executi

I agree it's unfortunate to lose some of the early events, but I think the remote capability is worth it.

**Comment by gaborcsardi** [comment]
OK. If somebody needs it, we can still re-add the old way as an alternative.

**Comment by wch** [comment]
Sounds good to me.

**Comment by johndharrison** [comment]
> I don't know if webdriver/phantom has a way of running some script before the scripts on the page run. I didn't look too carefully.

Using `/session/{{sessionid}}/phantom/execute` you can access the [PhantomJS API](http://phantomjs.org/api/) .  You can access various hooks such as [on-initialized](http://phantomjs.org/api/webpage/handler/on-initialized.html) and [on-load-started](http://phantomjs.org/api/webpage/handler/on-load-started.html).

**Comment by wch** [comment]
@johndharrison Interesting, I'll check that out. We'll still need to support the current behavior when testing on other (non-phantom) browsers, though.

**Pull request merged**
