### PR TITLE
add note in readme about downloading phantomjs

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! Can you pls update the `README.md` file as well?

**Comment by daattali** [comment]
I did this from within GitHub, I don't actually have a copy of the code locally..... I was too lazy to actually download the code and run it locally and render the readme. So, no :) Feel free to close my PR and do it yourself , I won't be offended

**Comment by gaborcsardi** [comment]
:) Yeah, this the problem of including auto-generated files in the repo. I don't like it, but there is no good way to avoid it for R packages.

**Comment by daattali** [comment]
Well, you could avoid it by running the rmarkdown->markdown conversion as a hook... but let's not go there

**Comment by gaborcsardi** [comment]
Local git hook? That still does not run if you edit on GH.

GH hook and then update from Travis or sg like this? Yes, let's not go
there. :)

**Pull request merged**
