### PR TITLE
First shot at tabs, closes #4

### LINKED ISSUE #4: Some nice API for tabs
E.g.
* a function to change tabs
* change tabs for `set_value` (?)
* change tabs for `expect_update` (?)

### PR DESCRIPTION
**Pull request by gaborcsardi**
My simple tests work fine.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Rebased, to re-run the CIs.

**Comment by wch** [comment]
Does it not work to simply use `getValue` and `setValue` on the `bootstrapTabInputBinding`?

**Comment by gaborcsardi** [comment]
Not all tabsets are inputs afaict. Only the ones that you supply an id for.

**Comment by gaborcsardi** [comment]
On the other hand we should probably have the same API for them as for inputs, so that we can easily use them in `setInputs` or `expect_update` or whatever we'll call it. 

So, yes, I should rewrite this.

**Comment by wch** [comment]
Oh, I see. So can tabsets with an id already be get/set with `get_value()` and `set_value()`?

**Comment by gaborcsardi** [comment]
Btw. one thing I was wondering about, whether it would be better to have a separate class for each input type. Currently they are not very different, but tables, plots, tabsets will be somewhat different and require different methods. 

So we could have an `input` (or `simpleinput`) class, and subclasses for tables, plots, tabs, etc.

**Comment by gaborcsardi** [comment]
> Oh, I see. So can tabsets with an id already be get/set with get_value() and set_value()?

Not currently. But see my other answer, I agree that they should. Actually, even the ones without an id, probably.

**Comment by wch** [comment]
I think it makes sense to treat tabs with id just like other inputs. For tabs without id, I think it's OK to have a different (and not as easy) API. If people want to have easy tests for tabs, I don't think it's too much to ask of them to use an id.

But if you want to have `get_value` and `set_value` for non-id tabs, don't let me stop you.

**Comment by wch** [comment]
It could make sense to have a subclasses for different inputs, but I need to get a better feel of the code before I weigh in on it.

**Comment by gaborcsardi** [comment]
> But if you want to have get_value and set_value for non-id tabs, don't let me stop you.

I think it is possible, and make sense. We would just allow widgets without a name. But once we have some API to get the widget object, like the current `app$get_tabsets()`, you can do `set_value()` and `get_value()` on them. 

Since they don't have names, the `setInputs` API would need to be different for them, though, which is not nice. Yeah, I am not sure. :)

**Comment by gaborcsardi** [comment]
> It could make sense to have a subclasses for different inputs, but I need to get a better feel of the code before I weigh in on it.

I was afraid that having ~10-15 classes would scare the users away, hence the current design. But we'll see how it goes.

**Comment by gaborcsardi** [comment]
OK, I rewrote it, so that tabs are proper widgets now, and they work with the usual `get_value()` and `set_value()` methods. There is an extra widget method that lists the tabs.

I only handle tabs with ids. If somebody wants to check other tabs, they can just do it at the HTML level.

Tabs work well in the reactive tests, e.g. here the `summary` output is only updated when it becomes visible by selecting the `Summary` tab:

```r
  app <- shinyapp$new("apps/006-tabsets-id")
  expect_update(app, dist = "unif", output = "plot")
  expect_update(app, tabs = "Summary", output = "summary")
```

**Comment by wch** [comment]
Great, so you came around to my point of view. :)

**Comment by gaborcsardi** [comment]
:)

**Pull request merged**
